# name of the data file for individual pattern
dataFileName: 'pattern.yml'
# details on our prototyper
patternlab:
  dest: './patternlab'
  version: '0.6.6'
  composer: 'php composer.phar'
# location of a library's global assets
globalAssets: './global-assets'
# location of our local patterns
localPatternsDir: './patterns'
# the github repository for this pattern library
githubrepo: pattern-library
# array of pattern libraries imported via npm
npmPatternRepos:
# templates imported into pattern lab after it is installed by composer
templates:
  -
    name: 'site-sass' # short name for this file
    src: './lib/templates/style.scss' # path to original template
    destDir: './patternlab/source/css/scss' # destination directory for this template
    destFile: 'style.scss' # final file name for this template
  -
    name: 'site-head'
    src: './lib/templates/head.twig'
    destDir: './patternlab/source/_meta'
    destFile: '_00-head.twig'
  -
    name: 'site-foot'
    src: './lib/templates/foot.twig'
    destDir: './patternlab/source/_meta'
    destFile: '_01-foot.twig'
# configs required for various file types
fileTypes:
  css: # css files
    globalAssetsSrc: # source(s) for any css files in global assets
      - '{{ globalAssets }}/styles/css/**/*.css'
    # destination for css from global assets
    globalAssetsDest: '{{ patternlab.dest }}/source/css/global-assets'
  fonts:
    globalAssetsSrc:
      - '{{ globalAssets }}/fonts/*'
      - '{{ globalAssets }}/fonts/**/*'
    globalAssetsDest: '{{ patternlab.dest }}/source/fonts'
  images:
    globalAssetsSrc:
      - '{{ globalAssets }}/images/*'
      - '{{ globalAssets }}/images/**/*'
    globalAssetsDest: '{{ patternlab.dest }}/source/images'
  js:
    prototyperSrcDir: '{{ patternlab.dest }}/source/js' # javascript directory inside source directory inside pattern lab
    globalAssetsSrc:
      - '{{ globalAssets }}/js/**/*.js'
  patterns:
    prototyperDestDir: '{{ patternlab.dest }}/source/_patterns' # destination for patterns inside pattern lab
  sass:
    prototyperSrcDir: '{{ patternlab.dest }}/source/css/scss' # sass directory inside source directory inside pattern lab
    prototyperSrc: '{{ patternlab.dest }}/source/css/scss/style.scss' # primary sass file
    prototyperDestDir: '{{ patternlab.dest }}/source/css' # location for compiled css file
    prototyperDest: '{{ patternlab.dest }}/source/css/style.css' # final compiled css file
    globalAssetsSrc:
      - '{{ globalAssets }}/styles/scss/**/*.scss'
    globalAssetsDest: '{{ patternlab.dest }}/source/css/scss/global-assets'
# configuration variables for gulp tasks
gulpTasks:
  # cloning a pattern
  clonePattern:
    taskName: clone # the task name
  # glob/inject tasks
  fileGlobInject:
    js:
      srcFile: '{{ patternlab.dest }}/source/_meta/_01-foot.twig'
      destDir: '{{ patternlab.dest }}/source/_meta'
    sass:
      srcFile: '{{ fileTypes.sass.prototyperSrc }}'
      destDir: '{{ fileTypes.sass.prototyperSrcDir }}'
  # sass compilation
  gulpSass:
    dependencies:
      - 'glob-inject-sass-all'
  # pattern importing tasks
  patternImporter:
    localPatterns: # patterns in THIS pattern library
      config:
        htmlTemplateDest: '{{ fileTypes.patterns.prototyperDestDir }}' # where the html templates will go when imported
        stylesDest: '{{ fileTypes.sass.prototyperSrcDir }}/local' # where the sass/css will go when imported
        scriptsDest: '{{ fileTypes.js.prototyperSrcDir }}/local' # where the javascript will go when imported
        convertCategoryTitles: false # convert category titles - converts 'atoms' to '00-atoms' for pattern lab
      taskName: 'patterns-import-local' # the task's name
      src:
        - './patterns/**/pattern.yml' # patterns to be imported by this task
    npmPatterns: # pattern libraries imported via NPM
      config:
        convertCategoryTitles: false
  # for replacing URLs when exporting library to github pages
  replaceUrl:
    ghPagesPrefix: '/{{ githubrepo }}'
    src:
      - '{{ patternlab.dest }}/source/**/*.json'
